//! Central action registry/spec for AETHER_02.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ActionSpec {
    pub tool: &'static str,
    pub action: &'static str,
    pub risk: &'static str,
    pub requires_force: bool,
    pub supports_dry_run: bool,
    pub feature_gate: Option<&'static str>,
    pub required_params: &'static [&'static str],
}

impl ActionSpec {
    #[must_use]
    pub fn to_json(self) -> serde_json::Value {
        serde_json::json!({
            "tool": self.tool,
            "action": self.action,
            "risk": self.risk,
            "requires_force": self.requires_force,
            "supports_dry_run": self.supports_dry_run,
            "feature_gate": self.feature_gate,
            "required_params": self.required_params,
        })
    }
}

pub const ACTION_SPECS: &[ActionSpec] = &[
    ActionSpec {
        tool: "file_system",
        action: "acl_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "acl_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "acl"],
    },
    ActionSpec {
        tool: "file_system",
        action: "append",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "content"],
    },
    ActionSpec {
        tool: "file_system",
        action: "chmod",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "mode"],
    },
    ActionSpec {
        tool: "file_system",
        action: "chown",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "owner"],
    },
    ActionSpec {
        tool: "file_system",
        action: "copy",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["source", "dest"],
    },
    ActionSpec {
        tool: "file_system",
        action: "delete",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "disk_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["device"],
    },
    ActionSpec {
        tool: "file_system",
        action: "disk_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "exists",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "list_dir",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "lvm_lvs",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "lvm_pvs",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "lvm_vgs",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "mkdir",
        risk: "moderate",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "mount",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["device", "target"],
    },
    ActionSpec {
        tool: "file_system",
        action: "mount_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "move",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["source", "dest"],
    },
    ActionSpec {
        tool: "file_system",
        action: "part_create",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: Some("AETHER_PARTITION_EDIT"),
        required_params: &["device", "start", "end"],
    },
    ActionSpec {
        tool: "file_system",
        action: "part_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "read",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "rename",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["source", "dest"],
    },
    ActionSpec {
        tool: "file_system",
        action: "stat",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "statvfs",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "swap_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "file_system",
        action: "swap_on",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["device"],
    },
    ActionSpec {
        tool: "file_system",
        action: "symlink_create",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["target", "link"],
    },
    ActionSpec {
        tool: "file_system",
        action: "symlink_delete",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "symlink_read",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "truncate",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "size"],
    },
    ActionSpec {
        tool: "file_system",
        action: "umount",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "write",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "content"],
    },
    ActionSpec {
        tool: "file_system",
        action: "xattr_delete",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "name"],
    },
    ActionSpec {
        tool: "file_system",
        action: "xattr_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path", "name"],
    },
    ActionSpec {
        tool: "file_system",
        action: "xattr_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "file_system",
        action: "xattr_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "name", "value"],
    },
    ActionSpec {
        tool: "file_system",
        action: "zfs_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "audio_list_sinks",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "audio_mute",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "audio_volume_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "audio_volume_set",
        risk: "moderate",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["volume"],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "clipboard_read",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "display_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "display_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "find_window",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["title"],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "keyboard_press",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["key"],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "keyboard_type",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["text"],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "list_windows",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "mouse_click",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["button"],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "mouse_move",
        risk: "moderate",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["x", "y"],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "mouse_position",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "screensaver_lock",
        risk: "moderate",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "gui_automation",
        action: "screenshot",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "acpi_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "acpi_wakeup",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "cpu_microcode_version",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "cpufreq_governor_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "cpufreq_governor_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "cpufreq_governor_set",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["governor"],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "gpu_amdgpu_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "gpu_nvidia_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "gpu_nvidia_smi",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "gpu_vulkan_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "hugepages_alloc",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["count"],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "hugepages_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "iommu_groups",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "iommu_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "irq_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "irq_set_affinity",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["irq", "mask"],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "kdump_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "pci_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["slot"],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "pci_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "thermal_cooling",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "thermal_temperature",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "thermal_zones",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "usb_authorize",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["device"],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "usb_deauthorize",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["device"],
    },
    ActionSpec {
        tool: "hardware_control",
        action: "usb_devices",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "adapter_down",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["interface"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "adapter_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["interface"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "adapter_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "adapter_speed",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["interface"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "adapter_stats",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["interface"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "adapter_up",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["interface"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "address_add",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["interface", "address"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "address_delete",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["interface", "address"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "address_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "bluetooth_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "bridge_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "connection_down",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["name"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "connection_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["name"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "connection_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "connection_up",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["name"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "dns_flush",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "dns_servers",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "firewall_rule_add",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["rule"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "firewall_rule_delete",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["rule"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "firewall_rules_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "hosts_read",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "hosts_write",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["content"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "network_namespace_create",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: Some("AETHER_NAMESPACE_CREATE"),
        required_params: &["name"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "network_namespace_delete",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: Some("AETHER_NAMESPACE_CREATE"),
        required_params: &["name"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "network_namespace_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "nftables_chain_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "nftables_table_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "route_add",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["route"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "route_delete",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["route"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "route_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "socket_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["filter"],
    },
    ActionSpec {
        tool: "network_manager",
        action: "socket_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "vlan_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "wifi_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "wifi_scan",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "network_manager",
        action: "wireguard_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "clean_cache",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "download",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "flatpak_install",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "flatpak_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "flatpak_remove",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "history",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "install",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "list_installed",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "list_repos",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "list_upgradable",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "nix_install",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "nix_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "nix_remove",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "remove",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "search",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "snap_install",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "snap_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "snap_remove",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["package"],
    },
    ActionSpec {
        tool: "package_manager",
        action: "upgrade_all",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "package_manager",
        action: "verify",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "process_control",
        action: "create",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["program"],
    },
    ActionSpec {
        tool: "process_control",
        action: "environ",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "fd_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "kill",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "limits",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "process_control",
        action: "memory_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "query_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "resume",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "set_nice",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["pid", "nice"],
    },
    ActionSpec {
        tool: "process_control",
        action: "set_priority",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["pid", "priority"],
    },
    ActionSpec {
        tool: "process_control",
        action: "signal",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["pid", "signal"],
    },
    ActionSpec {
        tool: "process_control",
        action: "suspend",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "threads",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "process_control",
        action: "tree",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "apparmor_profiles",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "apparmor_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "aslr_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "auditd_rules_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "auditd_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "core_pattern",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "cve_mitigations",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "dmesg_restrict",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "file_integrity_check",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "security_audit",
        action: "firewall_profile",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "firewall_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "ima_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "kernel_hardening",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "kernel_lsms",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "kernel_mitigations",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "kptr_restrict",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "lockdown_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "mmap_min_addr",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "ptrace_scope",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "secure_boot_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "selinux_booleans",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "selinux_mode",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "selinux_status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "tpm2_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "tpm2_pcrs",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "security_audit",
        action: "uefi_variables",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "analyze",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "cat",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "daemon_reload",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "default",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "disable",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "emergency",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "enable",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "isolate",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["target"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list_dependencies",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list_mounts",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list_paths",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list_sockets",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list_timers",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list_unit_files",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "list_units",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "mask",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "openrc_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "reload",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "rescue",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "reset_failed",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "restart",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "runit_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "service_manager",
        action: "show",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "start",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "status",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "stop",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "unmask",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["service"],
    },
    ActionSpec {
        tool: "service_manager",
        action: "user_services",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "anacron_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "at_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "boot_analyze",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "cron_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "cron_user_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "journal_disk_usage",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "journal_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "journal_query",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "sysctl_d_apply",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "sysctl_d_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "timer_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_automation",
        action: "tmpfiles_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "dconf_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["key"],
    },
    ActionSpec {
        tool: "system_config",
        action: "dconf_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "dconf_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["key", "value"],
    },
    ActionSpec {
        tool: "system_config",
        action: "environment_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "environment_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["key", "value"],
    },
    ActionSpec {
        tool: "system_config",
        action: "etc_config_read",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "system_config",
        action: "etc_config_write",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path", "content"],
    },
    ActionSpec {
        tool: "system_config",
        action: "gsettings_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["schema", "key"],
    },
    ActionSpec {
        tool: "system_config",
        action: "gsettings_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "gsettings_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["schema", "key", "value"],
    },
    ActionSpec {
        tool: "system_config",
        action: "hostname_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "hostname_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["hostname"],
    },
    ActionSpec {
        tool: "system_config",
        action: "kernel_cmdline_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "keyboard_layout",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "limits_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "locale_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "locale_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "locale_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["locale"],
    },
    ActionSpec {
        tool: "system_config",
        action: "modprobe_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "modprobe_load",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: Some("AETHER_MODULE_LOAD"),
        required_params: &["module"],
    },
    ActionSpec {
        tool: "system_config",
        action: "modprobe_unload",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: Some("AETHER_MODULE_LOAD"),
        required_params: &["module"],
    },
    ActionSpec {
        tool: "system_config",
        action: "os_release",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "sysctl_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["key"],
    },
    ActionSpec {
        tool: "system_config",
        action: "sysctl_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "sysctl_load",
        risk: "critical",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["path"],
    },
    ActionSpec {
        tool: "system_config",
        action: "sysctl_set",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["key", "value"],
    },
    ActionSpec {
        tool: "system_config",
        action: "timezone_get",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "timezone_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "timezone_set",
        risk: "moderate",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["timezone"],
    },
    ActionSpec {
        tool: "system_config",
        action: "udev_rules_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_config",
        action: "udev_trigger",
        risk: "critical",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "cpu_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "cpu_topology",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "disk_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "disk_partitions",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "gpu_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "hostname",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "kernel_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "kernel_modules",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "load_avg",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "memory_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["pid"],
    },
    ActionSpec {
        tool: "system_info",
        action: "os_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "os_release",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "pci_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "sensors_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "uptime",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "system_info",
        action: "usb_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "current_user",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "faillock_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "faillock_reset",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "group_add_user",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["username", "group"],
    },
    ActionSpec {
        tool: "user_management",
        action: "group_create",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["name"],
    },
    ActionSpec {
        tool: "user_management",
        action: "group_delete",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["name"],
    },
    ActionSpec {
        tool: "user_management",
        action: "group_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["name"],
    },
    ActionSpec {
        tool: "user_management",
        action: "group_remove_user",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["username", "group"],
    },
    ActionSpec {
        tool: "user_management",
        action: "groups_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "id",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "last_logins",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "nsswitch_conf",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "pam_list_modules",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "session_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["session"],
    },
    ActionSpec {
        tool: "user_management",
        action: "session_terminate",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["session"],
    },
    ActionSpec {
        tool: "user_management",
        action: "sessions_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "ssh_authorized_keys_add",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["username", "key"],
    },
    ActionSpec {
        tool: "user_management",
        action: "ssh_authorized_keys_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "ssh_authorized_keys_remove",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["username", "key"],
    },
    ActionSpec {
        tool: "user_management",
        action: "sudoers_read",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "user_create",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: Some("AETHER_TOKEN_MANIPULATION"),
        required_params: &["username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "user_delete",
        risk: "critical",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: Some("AETHER_TOKEN_MANIPULATION"),
        required_params: &["username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "user_info",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &["username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "user_lock",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "user_modify",
        risk: "critical",
        requires_force: false,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["args", "username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "user_unlock",
        risk: "dangerous",
        requires_force: true,
        supports_dry_run: true,
        feature_gate: None,
        required_params: &["username"],
    },
    ActionSpec {
        tool: "user_management",
        action: "users_list",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
    ActionSpec {
        tool: "user_management",
        action: "whoami",
        risk: "safe",
        requires_force: false,
        supports_dry_run: false,
        feature_gate: None,
        required_params: &[],
    },
];

#[must_use]
pub fn get(tool: &str, action: &str) -> Option<&'static ActionSpec> {
    ACTION_SPECS.iter().find(|spec| spec.tool == tool && spec.action == action)
}

#[must_use]
pub fn for_tool(tool: &str) -> Vec<&'static ActionSpec> {
    ACTION_SPECS.iter().filter(|spec| spec.tool == tool).collect()
}

#[must_use]
pub fn registry_json() -> serde_json::Value {
    serde_json::json!({
        "count": ACTION_SPECS.len(),
        "actions": ACTION_SPECS.iter().map(|spec| spec.to_json()).collect::<Vec<_>>(),
    })
}
